---
- name: Add docker repo GPG key
  apt_key:
    keyserver: hkp://p80.pool.sks-keyservers.net:80
    id: 58118E89F3A912897C070ADBF76221572C52609D
  become: yes

- name: Add official docker repo
  apt_repository:
    repo: deb https://apt.dockerproject.org/repo ubuntu-xenial main
  become: yes

- name: Install docker
  apt:
    name: docker-engine
    state: latest
    update_cache: yes
  become: yes

- name: Ensure docker group
  group:
    name: docker
    state: present
  become: yes

- name: Add current user to docker group
  user:
    name: "{{ mint_user_name }}"
    groups: docker
    append: yes
  become: yes
