---
- name: Add docker repo GPG key
  apt_key:
    keyserver: hkp://p80.pool.sks-keyservers.net:80
    id: 58118E89F3A912897C070ADBF76221572C52609D

- name: Add official docker repo
  apt_repository:
    repo: deb https://apt.dockerproject.org/repo ubuntu-xenial main

- name: Install docker
  apt:
    name: docker
    state: latest
    update_cache: yes
  become: yes
