---
- name: install stow
  apt:
    name: stow
    state: present
  become: yes

- name: get my dotfiles
  git:
    accept_hostkey: yes
    repo: "{{ dotfiles_git }}"
    dest: "{{ dotfiles_local }}"
  ignore_errors: yes
